development:
  adapter: mysql2
  database: nyim3_development
  pool: 5
  timeout: 5000
  encoding: utf8
  username: rails
  password: "rails"
  socket: /tmp/mysql.sock
  collation: utf8_general_ci
  
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: nyim3_production
  pool: 5
  timeout: 5000
  encoding: utf8
  username: rails
  password: "rails"
  #socket: /var/run/mysqld/mysqld.sock
  socket: /tmp/mysql.sock
  collation: utf8_general_ci
